[env:esp32-s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

# --- CONFIGURAÇÃO DO SISTEMA DE ARQUIVOS ---
# Define o tipo de sistema de arquivos
board_build.filesystem = littlefs

# --- BIBLIOTECAS NECESSÁRIAS ---
lib_deps =
    ottowinter/ESPAsyncWebServer-esphome@^3.1.0

# --- CONFIGURAÇÃO DO MONITOR SERIAL ---
monitor_speed = 115200